global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using UnityEngine;
global using Random = UnityEngine.Random;
global using ScriptableObject = UnityEngine.ScriptableObject;
global using static UnityEngine.ScriptableObject;
global using static UnityEngine.Object;
global using JFUtils;
global using JFUtils.Valheim;
global using JFUtils.WithPatch;
global using static ZoneSystem;
global using static JFUtils.ModBase;
global using static Terminal;
global using static Terminal.ConsoleCommand;
global using static ZoneSystem.ZoneLocation;
global using static ZoneSystem.ZoneVegetation;
global using static Heightmap;
global using static Heightmap.Biome;
global using static ItemDrop;
global using static ItemDrop.ItemData;
global using static SuperSigns.Plugin;
global using static BepInEx.BepInDependency;
global using static Skills;
global using JetBrains.Annotations;
global using TMPro;
global using Component = UnityEngine.Component;
global using CompressionLevel = System.IO.Compression.CompressionLevel;
global using static MessageHud.MessageType;
global using static Player;
global using static Player.PlacementStatus;